name: Deploy branch to heroku

on:
  push:
    branches: [heroku-deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checks out repo
        if: github.repository == 'watchpartyappmain/watchparty-server-test'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run install on backend and test
        run: |
          npm install
          npm run testunit
        env:
          CI: true
          NODE_ENV: test
          TEST_DB_HOSTNAME: ${{ secrets.TEST_DB_HOSTNAME }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          TEST_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "watch-party-test-api"
        run: |
          git push https://heroku:${HEROKU_API_TOKEN}@git.heroku.com/${HEROKU_APP_NAME}.git heroku-deploy:master --force
